### ISSUE TITLE
Docs regarding backup restore has some incorrect info

### ISSUE THREAD

**Issue by gertzakis** [nautobot/helm-charts#366]
The documentation regarding backup and restore procedure, has some misleading guidelines. Specifically, it is missing the `namespace` part on some commands, and pulls the wrong secret regarding the nautobot database.

**Comment by whitej6** [comment]
Also IIRC namespace can come from an env variable or the context you're targeting in the kube config. 

Some other options could be some quick start docs to show the different permutations of this including the most common practice of `alias k="kubectl -n <my namespace>`. 

And some examples of using k9s

And the last can of worms is have cli tools for rancher and OpenShift do things a little differently BUT from my experience are based on kubectl or are thin wrappers that sit on top of kubectl with opinionated abstractions for things like auth and more specifically for OpenShit you set your project context and most OC commands don't need the namespace because of their opinionated layer on top.


I very much appreciate the issue and believe we should do a review on things like this in the docs. We may want an initial fix of adding namespace references but later look at adding some sections on "my first kubernetes deployments" to cover things mentioned above.

**Comment by gertzakis** [comment]
Hmm, I see your point. IMHO the namespace flag should be removed, because the same charts are used in OpenShift, and also every admin has his own preferences of working with k8s :) Just saw the inconsistency and wanted to point it out. 
The initial reason I opened the issue is the secret data path. Meaning, it should get `jsonpath="{.data.password}"` which is the nautobot's user password to dump the DB.
