### ISSUE TITLE
Image moved to media folder is removed after deployment

### ISSUE THREAD

**Issue by theNickMagee** [nautobot/helm-charts#445]
Nautobot version: 2.2.9
Python 3.10

We are using the most resent helm chart (2.2.0) to deploy Nautobot. In the Docker build step, we copy our custom PNG logo to the `/opt/nautobot/media` directory, however it seems later in the process nautobot overwrites this directory with the folders `devicetype-images`, `health_check_storage_test`, and `image-attchments`.

Is there a workaround for this? The behavior started happening after several helm chart upgrades (most likely due to [this PR](https://github.com/nautobot/helm-charts/pull/391))

Thanks.

**Comment by gertzakis** [comment]
Never though of this use case tbh. I would try to create a PVC by enabling it and copy (`kubectl cp`) the logo to `/opt/nautobot/media` as a workaround. 
In order to fix this though, changing the chart to only create a `volumeMount` in the deployment if `persistenceMediaFiles` is enabled will probably do the trick.
